# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 631)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(200, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.open_btn.setFont(font)
        self.open_btn.setAutoFillBackground(False)
        self.open_btn.setStyleSheet("QPushButton { background-color: rgb(255, 132, 139); border-radius: 3px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(245, 69, 234); }")
        self.open_btn.setAutoDefault(False)
        self.open_btn.setObjectName("open_btn")
        self.index_btn = QtWidgets.QPushButton(self.centralwidget)
        self.index_btn.setGeometry(QtCore.QRect(680, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.index_btn.setFont(font)
        self.index_btn.setStyleSheet("QPushButton { background-color: rgb(25, 232, 39); border-radius: 3px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(45, 199, 234); }")
        self.index_btn.setObjectName("index_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(580, 100, 351, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setRowCount(7)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(162)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(61)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 531, 411))
        self.label.setAcceptDrops(False)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.display_btn = QtWidgets.QPushButton(self.centralwidget)
        self.display_btn.setGeometry(QtCore.QRect(190, 520, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.display_btn.setFont(font)
        self.display_btn.setAutoFillBackground(False)
        self.display_btn.setStyleSheet("QPushButton { background-color: rgb(55, 132, 139); border-radius: 3px; color: rgb(55, 255, 255); } QPushButton:hover { background-color: rgb(45, 69, 34); }")
        self.display_btn.setAutoDefault(False)
        self.display_btn.setObjectName("display_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像检索"))
        self.open_btn.setText(_translate("MainWindow", "打开图像"))
        self.index_btn.setText(_translate("MainWindow", "图像检索"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "图像名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "相似度"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#550000;\">图像检索</span></p><p align=\"center\"><a href=\"http://www.ruanyifeng.com/blog/2011/07/principle_of_similar_image_search.html\"><span style=\" font-size:26pt; text-decoration: underline; color:#55557f;\">基于感知哈希算法</span></a></p><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#00557f;\">Python 3 &amp; Qt 5 实现</span></p></body></html>"))
        self.display_btn.setText(_translate("MainWindow", "显示图像库"))
        self.action.setText(_translate("MainWindow", "打开文件"))

